### PR TITLE
Update rustls to 0.19.0

### PR DESCRIPTION
**Pull request by tinywombat765**
All tests pass on my end.

### CODE REVIEW

**Comment by ghost** [comment]
Thanks for the PR! Refer to this PR on how to fix CI errors, should be easy: https://github.com/smol-rs/async-io/pull/41/files

**Comment by tinywombat765** [comment]
That CI failure seems to be a compiler bug.

**Comment by tinywombat765** [comment]
https://github.com/rust-lang/rust/issues/79487

**Comment by tinywombat765** [comment]
@stjepang can this get merged? Nightly should pass now if rerun.

**Comment by ghost** [comment]
Published v0.2.0

**Pull request merged**
